# Centralized server-side game configuration

# Map
MAP_WIDTH = 1920
MAP_HEIGHT = 1080

# Player
PLAYER_MAX_HP = 1000
REGEN_INTERVAL_SEC = 4.0  # seconds since last_hit to start regen
REGEN_AMOUNT_PER_TICK = 3  # hp per game_loop tick when regen applies

# Walls
WALL_BLOCK_SIZE = 32
WALL_LIFETIME_SEC = 20

# Smokes
SMOKE_DEFAULT_RADIUS = 180
SMOKE_DEFAULT_DURATION = 15
SMOKE_APPEAR_ANIM_SEC = 0.4

# Bullets (defaults)
BULLET_MAX_LIFETIME_SEC = 10
BULLET_HIT_RADIUS = 30
BULLET_DEFAULT_DAMAGE = 300

# Missile
MISSILE_TRACK_RANGE = 500
MISSTLE_HIT_RADIUS = 60
MISSILE_DAMAGE = 600

# Turret
TURRET_RANGE = 450
TURRET_CD = 0.4
TURRET_BULLET_SPEED = 16
TURRET_BULLET_DAMAGE = 50
TURRET_MAX_DIST = 450
TURRET_INITIAL_HP = 800
TURRET_SELF_DECAY_PER_SEC = 25.0
TURRET_PLACE_LIMIT = 150.0

# Iaido (Dash)
IAIDO_DISTANCE = 100.0
IAIDO_DAMAGE = 350
IAIDO_WIDTH = 28.0  # path hit thickness comparable to player radius
IAIDO_CD_SEC = 1.5
IAIDO_SPEED = 700.0  # pixels per second for backend dash interpolation
