# Centralized server-side game configuration

# Map
MAP_WIDTH = 1920
MAP_HEIGHT = 1080

# Player
PLAYER_MAX_HP = 1000
REGEN_INTERVAL_SEC = 4.0  # seconds since last_hit to start regen
REGEN_AMOUNT_PER_TICK = 3  # hp per game_loop tick when regen applies

# Perk tuning
# 漏洞（被动）调整：回血强化倍率与死亡状态下是否允许回血
REGEN_BONUS_MULTIPLIER = 1.5  # 有“增强回血效率”时的倍率
ALLOW_REGEN_WHEN_DEAD = True  # 有“死亡后继续回血”时生效的开关

# Walls
WALL_BLOCK_SIZE = 32
WALL_LIFETIME_SEC = 20

# Smokes
SMOKE_DEFAULT_RADIUS = 180
SMOKE_DEFAULT_DURATION = 15
SMOKE_APPEAR_ANIM_SEC = 0.4

# Bullets (defaults)
BULLET_MAX_LIFETIME_SEC = 10
BULLET_HIT_RADIUS = 30
BULLET_DEFAULT_DAMAGE = 300

# Missile
MISSILE_TRACK_RANGE = 500
MISSTLE_HIT_RADIUS = 60
MISSILE_DAMAGE = 600

# Turret
TURRET_RANGE = 450
TURRET_CD = 0.4
TURRET_BULLET_SPEED = 15
TURRET_BULLET_DAMAGE = 30
TURRET_MAX_DIST = 450
TURRET_INITIAL_HP = 800
TURRET_SELF_DECAY_PER_SEC = 25.0
TURRET_PLACE_LIMIT = 150.0

# Iaido
IAIDO_DISTANCE = 480.0
IAIDO_DAMAGE = 170
IAIDO_WIDTH = 40.0
IAIDO_SPEED = 1800.0
