# Centralized server-side game configuration (single source of truth).
# Frontend receives a subset via GET /api/game-config for rendering / prediction.

# Map
MAP_WIDTH = 1920
MAP_HEIGHT = 1080

# Player
PLAYER_MAX_HP = 1000
PLAYER_SPEED = 4.0
PLAYER_RADIUS = 30
REGEN_INTERVAL_SEC = 4.0
REGEN_AMOUNT_PER_TICK = 3

# Perk tuning
REGEN_BONUS_MULTIPLIER = 1.5
ALLOW_REGEN_WHEN_DEAD = True

# Weapon switching
SWITCH_WEAPON_CD_SEC = 3.0

# Walls
WALL_BLOCK_SIZE = 32
WALL_LIFETIME_SEC = 20
WALL_PLACE_RANGE = 400.0
WALL_CD_SEC = 2.5

# Smokes
SMOKE_DEFAULT_RADIUS = 180
SMOKE_DEFAULT_DURATION = 15
SMOKE_APPEAR_ANIM_SEC = 0.4
SMOKE_PLACE_RANGE = 400.0
SMOKE_CD_SEC = 5.0

# Single rifle
BULLET_RANGE = 900.0
BULLET_SPEED = 30.0
BULLET_CD_SEC = 1.0
BULLET_RADIUS = 10
BULLET_DAMAGE = 300
BULLET_MAX_LIFETIME_SEC = 10
BULLET_HIT_RADIUS = 30
BULLET_DEFAULT_DAMAGE = 300  # legacy alias used by game_logic

# Shotgun
SHOTGUN_RANGE = 500.0
SHOTGUN_SPEED = 40.0
SHOTGUN_CD_SEC = 1.8
SHOTGUN_DAMAGE = 160
SHOTGUN_PELLET_COUNT = 6
SHOTGUN_SPREAD = 0.5235987755982988  # pi / 6

# Missile
MISSILE_RANGE = 9999.0
MISSILE_SPEED = 16.0
MISSILE_CD_SEC = 2.3
MISSILE_DAMAGE = 600
MISSILE_TRACK_RANGE = 500
MISSTLE_HIT_RADIUS = 60  # typo kept for existing imports

# Turret
TURRET_RANGE = 450
TURRET_FIRE_CD_SEC = 0.4
TURRET_BULLET_SPEED = 15
TURRET_BULLET_DAMAGE = 30
TURRET_MAX_DIST = 450
TURRET_INITIAL_HP = 800
TURRET_SELF_DECAY_PER_SEC = 25.0
TURRET_PLACE_LIMIT = 150.0
TURRET_PLACE_CD_SEC = 5.0

# Cross Bomb
CROSS_BOMB_FUSE_SEC = 2.0
CROSS_BOMB_DAMAGE = 420
CROSS_BOMB_ARM_LENGTH = 220.0
CROSS_BOMB_ARM_HALF_WIDTH = 20.0
CROSS_BOMB_EXPLOSION_DURATION = 0.6
CROSS_BOMB_MAX_ACTIVE_PER_PLAYER = 3
CROSS_BOMB_PLACE_DISTANCE = 540.0
CROSS_BOMB_CD_SEC = 0.5

# Iaido
IAIDO_MIN_DISTANCE = 150.0
IAIDO_DISTANCE = 480.0
IAIDO_DAMAGE = 170
IAIDO_WIDTH = 40.0
IAIDO_SPEED = 1800.0
IAIDO_HOLD_MAX_SEC = 1.0
IAIDO_CHARGE_MAX = 3
IAIDO_CHARGE_INTERVAL_SEC = 2.0
IAIDO_CHARGE_INTERVAL_EMPTY_SEC = 2.0


def as_client_dict() -> dict:
    """Values the frontend needs for rendering, aim guides, and optimistic UI."""
    return {
        "MAP_WIDTH": MAP_WIDTH,
        "MAP_HEIGHT": MAP_HEIGHT,
        "PLAYER_SPEED": PLAYER_SPEED,
        "MAX_HP": PLAYER_MAX_HP,
        "PLAYER_RADIUS": PLAYER_RADIUS,
        "SWITCH_WEAPON_CD": int(SWITCH_WEAPON_CD_SEC * 1000),
        "BULLET_RANGE": BULLET_RANGE,
        "BULLET_SPEED": BULLET_SPEED,
        "BULLET_CD": int(BULLET_CD_SEC * 1000),
        "BULLET_RADIUS": BULLET_RADIUS,
        "BULLET_DAMAGE": BULLET_DAMAGE,
        "SHOTGUN_RANGE": SHOTGUN_RANGE,
        "SHOTGUN_SPEED": SHOTGUN_SPEED,
        "SHOTGUN_CD": int(SHOTGUN_CD_SEC * 1000),
        "SHOTGUN_DAMAGE": SHOTGUN_DAMAGE,
        "SHOTGUN_PELLET_COUNT": SHOTGUN_PELLET_COUNT,
        "MISSILE_RANGE": MISSILE_RANGE,
        "MISSILE_SPEED": MISSILE_SPEED,
        "MISSILE_CD": int(MISSILE_CD_SEC * 1000),
        "MISSILE_DAMAGE": MISSILE_DAMAGE,
        "WALL_CD": int(WALL_CD_SEC * 1000),
        "WALL_PLACE_RANGE": WALL_PLACE_RANGE,
        "WALL_BLOCK_SIZE": WALL_BLOCK_SIZE,
        "SMOKE_RADIUS": SMOKE_DEFAULT_RADIUS,
        "SMOKE_DURATION": SMOKE_DEFAULT_DURATION,
        "SMOKE_PLACE_RANGE": SMOKE_PLACE_RANGE,
        "SMOKE_CD": int(SMOKE_CD_SEC * 1000),
        "TURRET_PLACE_RANGE": TURRET_PLACE_LIMIT,
        "TURRET_HP": TURRET_INITIAL_HP,
        "TURRET_DAMAGE": TURRET_BULLET_DAMAGE,
        "TURRET_RANGE": TURRET_RANGE,
        "TURRET_CD": int(TURRET_PLACE_CD_SEC * 1000),
        "CROSS_BOMB_CD": int(CROSS_BOMB_CD_SEC * 1000),
        "CROSS_BOMB_MAX_DISTANCE": CROSS_BOMB_PLACE_DISTANCE,
        "CROSS_BOMB_FUSE_MS": int(CROSS_BOMB_FUSE_SEC * 1000),
        "CROSS_BOMB_DAMAGE": CROSS_BOMB_DAMAGE,
        "CROSS_BOMB_ARM_LENGTH": CROSS_BOMB_ARM_LENGTH,
        "CROSS_BOMB_ARM_WIDTH": CROSS_BOMB_ARM_HALF_WIDTH * 2,
        "CROSS_BOMB_EXPLOSION_DURATION_MS": int(CROSS_BOMB_EXPLOSION_DURATION * 1000),
        "CROSS_BOMB_MAX_ACTIVE": CROSS_BOMB_MAX_ACTIVE_PER_PLAYER,
        "IAIDO_MIN_DISTANCE": IAIDO_MIN_DISTANCE,
        "IAIDO_DISTANCE": IAIDO_DISTANCE,
        "IAIDO_DAMAGE": IAIDO_DAMAGE,
        "IAIDO_CHARGE_MAX": IAIDO_CHARGE_MAX,
        "IAIDO_CHARGE_INTERVAL_MS": int(IAIDO_CHARGE_INTERVAL_SEC * 1000),
        "IAIDO_CHARGE_INTERVAL_EMPTY_MS": int(IAIDO_CHARGE_INTERVAL_EMPTY_SEC * 1000),
        "IAIDO_WIDTH": IAIDO_WIDTH,
        "IAIDO_HOLD_MAX_MS": int(IAIDO_HOLD_MAX_SEC * 1000),
    }
